version: 0.2

env:
  shell: bash
  variables:
    AWS_ACCOUNT_ID: '784074879813'
    IMAGE_REPO_NAME: 'nae-user-managmement-api'

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing CI/CD dependencies"
      - npm ci

  pre_build:
    on-failure: ABORT
    commands:
      - echo "Running Tests"
      - npm run test

  build:
    on-failure: ABORT
    commands:
      - echo "Building Docker Image"
      - docker build -t $IMAGE_REPO_NAME:Nae3x-$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO_NAME:Nae3x-$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:Nae3x-$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    on-failure: ABORT
    commands:
      - echo "Pushing image to ECR"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:Nae3x-$CODEBUILD_RESOLVED_SOURCE_VERSION
